tinyMCE.addI18n('en.superemotions_dlg',{
title : 'Add Emoticon / Icon',
desc : 'Emoticons / Icons',
arrow : 'Arrow Icon',
exclaim : 'Exclaimaition Mark',
question : 'Question Mark',
idea : 'Lightbulb / Idea',
smile : 'Smile',
biggrin : 'Big Grin',
lol : 'Laughing Out Loud',
wink : 'Wink',
cool : 'Cool',
neutral : 'Neutral',
confused : 'Confused',
razz : 'Razzberry',
surprised : 'Suprised',
eek : 'EEK',
redface : 'Redfaced / Embarassed',
rolleyes : 'Rolling Eyes',
mad : 'Mad',
sad : 'Sad',
cry : 'Crying',
mrgreen : 'Green with Envy',
evil : 'Evil',
twisted : 'Evil and Twisted'
});

